export const authErrorMessages = {
  USER_EXISTS: 'This user already exists',
  USER_NOT_CREATE: 'User not create',
  USER_NOT_FOUND: 'User not found',
  USER_NOT_ACTIVATED: 'User not activated',
  USER_ACTIVATED: 'Your account has been activated. Login please!',
  USER_BLOCKED: 'User is BLOCKED',
  SIGN_IN_WITH: 'Sign in with ',
  ROLE_NOT_VALID: 'Role not valid',
  NO_ACCESS_TOKEN: 'No access token',
  NO_REFRESH_TOKEN: 'No refresh token',
  NO_ACTIVATE_TOKEN: 'No activate token',
  TOKEN_NOT_FOUND_IN_DB: 'Token not found in database',
  NOT_VALID_ACCESS_TOKEN: 'Not valid access token',
  NOT_VALID_REFRESH_TOKEN: 'Not valid refresh token',
  NOT_VALID_ACTIVATE_TOKEN: 'Not valid activate link. Enter your email and I’m re-sending you email for activation.',
  AUTH_TOKENS_EXIST: 'You are logged in. Auth tokens exist',
  PASSWORDS_NOT_CHANGED: 'Password do not changed!',
  PASSWORDS_NOT_MATCH: 'Password do not match!',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden'
};
